name: Build Web

on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.24.3
            - run: flutter pub get

            - run: flutter analyze  --no-fatal-warnings --no-fatal-infos lib/main.dart               

            - uses: bluefireteam/flutter-gh-pages@v7
              with:
                baseHref: /happy_programmers_day/
                customArgs: --target="lib/main.dart"
    
    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.24.3
            - run: flutter pub get

            - name: Install Visual Studio Build Tools
              run: choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --includeOptional"

            - run: flutter build windows --release lib/main.dart